# Generated by Django 3.1.8 on 2023-04-06 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carrusel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='img/carrusel/', verbose_name='Imagen')),
                ('texto', models.CharField(default='', max_length=100, verbose_name='Texto')),
            ],
            options={
                'verbose_name': 'Elemento de carrusel',
                'verbose_name_plural': '01- Carrusel',
            },
        ),
        migrations.CreateModel(
            name='categorias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(default='', max_length=100, verbose_name='Categoría')),
            ],
            options={
                'verbose_name_plural': '08- Categorias',
            },
        ),
        migrations.CreateModel(
            name='conocenos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sobreNosotros', models.CharField(default='Sobre nosotros', max_length=100, verbose_name='Sobre nosotros')),
                ('condiciones', models.CharField(default='Condiciones de uso', max_length=100, verbose_name='Condiciones de uso')),
                ('envio', models.CharField(default='Envíos y Devoluciones', max_length=100, verbose_name='Envíos y Devoluciones')),
                ('politica', models.CharField(default='Política de Privacidad', max_length=100, verbose_name='Política de Privacidad')),
            ],
            options={
                'verbose_name': '04- Conócenos',
            },
        ),
        migrations.CreateModel(
            name='contactenos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telef', models.CharField(default='', max_length=100, verbose_name='Teléfono')),
                ('email', models.EmailField(default='soscombos@gmail.com', max_length=100, verbose_name='Correo')),
                ('email_en', models.URLField(max_length=1000, verbose_name='Enlace de correo')),
            ],
            options={
                'verbose_name': '05- Contáctenos',
            },
        ),
        migrations.CreateModel(
            name='general',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=14, unique=True, verbose_name='Nombre de la empresa')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='img/logo/', verbose_name='Logo')),
                ('email', models.EmailField(default='soscombos@gmail.com', max_length=100, verbose_name='Correo de pedidos')),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Precio de envio')),
                ('entrega', models.CharField(default='', max_length=50, unique=True, verbose_name='Tiemp de entrega')),
                ('id_paypal', models.CharField(blank=True, default='', max_length=100, null=True, unique=True, verbose_name='Id de Paypal')),
            ],
            options={
                'verbose_name': '00- General',
            },
        ),
        migrations.CreateModel(
            name='productosDomicilio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(default='img/banner 2.jpg', upload_to='img/Productos Domicilio/', verbose_name='Imagen')),
                ('encabezado', models.CharField(max_length=100, verbose_name='Encabezado')),
                ('texto', models.CharField(max_length=1000, verbose_name='Texto')),
            ],
            options={
                'verbose_name': '03- Pedidos a domicilio',
            },
        ),
        migrations.CreateModel(
            name='subscripciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, verbose_name='Correo')),
            ],
            options={
                'verbose_name': 'subscripción',
                'verbose_name_plural': '06- Subscripciones',
            },
        ),
        migrations.CreateModel(
            name='ubicaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(max_length=100, verbose_name='ubicacion')),
            ],
        ),
        migrations.CreateModel(
            name='venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lista', models.TextField(max_length=99999999, verbose_name='Lista de compra')),
                ('precio_total', models.FloatField(verbose_name='Precio total')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de quien paga')),
                ('nombre2', models.CharField(max_length=100, verbose_name='Nombre de quien recibe')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo del cliente')),
                ('direccion', models.CharField(max_length=200, verbose_name='Direccion')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Cudad')),
                ('pais', models.CharField(max_length=100, verbose_name='País')),
                ('telefono', models.CharField(max_length=30, verbose_name='Teléfono de quien paga')),
                ('telefono2', models.CharField(max_length=30, verbose_name='Teléfono de quien recibe')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
            },
        ),
        migrations.CreateModel(
            name='subCategorias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategoria', models.CharField(default='', max_length=100, verbose_name='Subcategoría')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categorias', unique=True, verbose_name='Categoría')),
            ],
            options={
                'verbose_name_plural': '09-Subcategorias',
            },
        ),
        migrations.CreateModel(
            name='productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantventas', models.PositiveIntegerField(auto_created=True, default=0, editable=False, verbose_name='Cantidad de ventas')),
                ('activ', models.BooleanField(default=True, verbose_name='Mostrar')),
                ('imagen', models.ImageField(upload_to='img/productos/', verbose_name='Imagen')),
                ('nombre', models.CharField(default='', max_length=100, verbose_name='Nombre')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precio')),
                ('mejor', models.BooleanField(default=True, verbose_name='Marcar como uno de los mejores productos')),
                ('especial', models.BooleanField(default=True, verbose_name='Oferta especial')),
                ('subcategoria', models.ManyToManyField(to='app.subCategorias')),
                ('ubicaciones', models.ManyToManyField(to='app.ubicaciones')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': '02- Productos',
            },
        ),
    ]
