# Generated by Django 3.1.8 on 2023-03-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='general',
            name='paginas',
        ),
        migrations.AddField(
            model_name='general',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Precio'),
        ),
    ]
