# Generated by Django 3.1.8 on 2023-03-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20230317_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='general',
            name='id_paypal',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='Id de Paypal'),
        ),
        migrations.AlterField(
            model_name='general',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Precio de envio'),
        ),
    ]
