# Generated by Django 3.1.8 on 2023-03-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20230317_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general',
            name='id_paypal',
            field=models.CharField(blank=True, default='', max_length=100, null=True, unique=True, verbose_name='Id de Paypal'),
        ),
    ]
