# Generated by Django 3.1.8 on 2023-03-18 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20230317_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactenos',
            name='email_en',
            field=models.URLField(max_length=1000, verbose_name='Enlace de correo'),
        ),
    ]
