# Generated by Django 3.1.8 on 2023-03-19 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20230318_0114'),
    ]

    operations = [
        migrations.CreateModel(
            name='carrusel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='img/carrusel/', verbose_name='Imagen')),
                ('texto', models.CharField(default='', max_length=100, verbose_name='Texto')),
            ],
            options={
                'verbose_name': 'Elemento de carrusel',
                'verbose_name_plural': '01- Carrusel',
            },
        ),
        migrations.AlterModelOptions(
            name='general',
            options={'verbose_name': '00- General'},
        ),
    ]
