# Generated by Django 3.1.8 on 2023-03-19 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20230319_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrusel',
            name='texto',
            field=models.CharField(default='', max_length=1000, verbose_name='Texto'),
        ),
    ]
