# Generated by Django 3.1.8 on 2023-03-19 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20230319_0234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrusel',
            old_name='logo',
            new_name='imagen',
        ),
    ]
