# Generated by Django 3.1.8 on 2023-03-19 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20230319_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrusel',
            name='texto',
            field=models.CharField(default='', max_length=100, verbose_name='Texto'),
        ),
    ]
