# Generated by Django 3.1.8 on 2023-03-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20230319_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general',
            name='nombre',
            field=models.CharField(default='', max_length=15, unique=True, verbose_name='Nombre de la empresa'),
        ),
    ]
