# Generated by Django 3.1.8 on 2023-03-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20230326_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=100, verbose_name='Product`s Name')),
                ('precio', models.FloatField(verbose_name='Price (discounts included)')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Product`s Quantity')),
                ('precio_total', models.FloatField(verbose_name='Total Price')),
                ('nombre', models.CharField(max_length=100, verbose_name='Client`s Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Client`s Email')),
                ('fecha', models.DateTimeField(verbose_name='Date')),
                ('direccion', models.CharField(max_length=200, verbose_name='Address')),
                ('ciudad', models.CharField(max_length=100, verbose_name='City')),
                ('codigo_postal', models.CharField(max_length=30, verbose_name='ZipCode')),
                ('telefono', models.CharField(max_length=30, verbose_name='Phone')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comment')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
            },
        ),
    ]
