# Generated by Django 3.1.8 on 2023-03-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_venta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='codigo_postal',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='comentario',
        ),
        migrations.AddField(
            model_name='venta',
            name='pais',
            field=models.CharField(default='', max_length=100, verbose_name='País'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venta',
            name='cantidad',
            field=models.PositiveIntegerField(verbose_name='Cantidad de unidades del producto'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='ciudad',
            field=models.CharField(max_length=100, verbose_name='Cudad'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='direccion',
            field=models.CharField(max_length=200, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo del cliente'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre del cliente'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='precio',
            field=models.FloatField(verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='precio_total',
            field=models.FloatField(verbose_name='Precio total'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='producto',
            field=models.CharField(max_length=100, verbose_name='Nombre del producto'),
        ),
    ]
