# Generated by Django 3.1.8 on 2023-04-05 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_general_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='general',
            name='email',
            field=models.EmailField(default='soscombos@gmail.com', max_length=100, verbose_name='Correo de pedidos'),
        ),
    ]
